Repository JoselFO8/sportShop-client, pull requests merged in 2022-07, with the labels that each got.

#3 Feature navbar generate html
  package-lock.json
  package.json
  src/App.tsx
  src/components/Navbar/Navbar.tsx
Labels: documentation

#7 Subo actions-types, cambios en Navbar, action y reducer
  src/components/Home/Home.tsx
  src/components/Navbar/Navbar.tsx
  src/redux/action/index.ts
  src/redux/actionsTypes/actionsTypes.ts
  src/redux/reducer/index.ts
Labels: enhancement

#13 CSS Products & Cards
  package-lock.json
  package.json
  src/components/Card/Card.module.scss
  src/components/Card/Card.tsx
  src/components/Navbar/Navbar.tsx
  src/components/Products/Products.module.scss
  src/components/Products/Products.tsx
Labels: enhancement

#26 Se agrega categorias y respectivos estilos
  src/App.tsx
  src/assets/Accessories/Accessories_1.webp
  src/assets/Accessories/Accessories_2.jpg
  src/assets/Accessories/Accessories_3.jpg
  src/assets/Clothes/Clothes_1.jpg
  src/assets/Clothes/Clothes_2.jpg
  src/assets/Clothes/Clothes_3.jpg
  src/assets/Clothes/Clothes_4.jpg
  src/assets/Footwear/Footwear_1.jpg
  src/assets/Footwear/Footwear_2.jpg
  src/assets/Footwear/Footwear_3.jpg
  src/assets/Gender/Man_1.jpg
  src/assets/Gender/Man_2.jpg
  src/assets/Gender/Woman_1.jpg
  src/assets/Gender/Woman_2.jpg
  src/components/Card/Card.module.scss
  src/components/Categories/Categories.module.scss
  src/components/Categories/Categories.tsx
  src/components/Categories/Clothing.tsx
  src/components/Categories/Kids.tsx
  src/components/Categories/Man.tsx
  src/components/Categories/Shoes.tsx
  src/components/Categories/Woman.tsx
  src/components/Categories/accesories.tsx
  src/components/Home/Home.tsx
  src/components/Products/Products.tsx
  src/components/Subcategory/Subcategory.tsx
Labels: enhancement

#30 Se arregla detail y subcategory
  src/components/Card/Card.tsx
  src/components/Subcategory/Subcategory.tsx
  src/redux/action/index.ts
  src/redux/reducer/index.ts
Labels: bug

#31 Navbar
  src/components/Navbar/Navbar.tsx
Labels: enhancement

#43 Componente purchase y checkout
  .env
  package-lock.json
  package.json
  src/App.tsx
  src/components/Checkout/Categories/CheckoutForm.module.scss
  src/components/Checkout/Categories/CheckoutForm.tsx
  src/components/Navbar/NavBar.module.scss
  src/components/Navbar/Navbar.tsx
  src/components/Products/Products.tsx
  src/components/Purchase/Purchase.module.scss
  src/components/Purchase/Purchase.tsx
Labels: enhancement

#48 Add actions - Get users & shoppinglist
  package-lock.json
  package.json
  src/components/Checkout/Categories/CheckoutForm.tsx
  src/components/Checkout/CheckoutForm.module.scss
  src/components/Checkout/CheckoutForm.tsx
  src/components/Products/Products.tsx
  src/components/Purchase/Purchase.module.scss
  src/components/Purchase/Purchase.tsx
  src/redux/action/index.ts
  src/redux/actionsTypes/actionsTypes.ts
  src/redux/reducer/index.ts
Labels: bug, enhancement

#58 Nueva categoria y cambio de estilos
  src/assets/Accessories/Accessories_1.jpg
  src/assets/Clothes/Clothes_11.jpg
  src/assets/Clothes/Clothes_2.jpg
  src/assets/Clothes/Clothes_5.jpg
  src/assets/Clothes/Clothes_6.jpg
  src/assets/Clothes/Clothes_7.jpg
  src/assets/Clothes/Clothes_8.jpg
  src/assets/Footwear/Footwear_2.jpg
  src/assets/Gender/Kid_1.jpg
  src/assets/Gender/Kids_1.jpg
  src/assets/Gender/Kids_2.jpg
  src/assets/Gender/Kids_3.jpg
  src/assets/Gender/Man_2.jpg
  src/assets/Gender/Woman_2.jpg
  src/components/Card/Card.module.scss
  src/components/Card/Card.tsx
  src/components/Categories/Categories.module.scss
  src/components/Categories/Categories.tsx
  src/components/Products/Products.tsx
  src/components/Purchase/Purchase.module.scss
  src/components/Purchase/Purchase.tsx
  src/components/Subcategory/Subcategories.module.scss
Labels: bug, enhancement

#63 Fix checkout post
  src/assets/Accessories/Accessories_1.jpg
  src/assets/Accessories/Accessories_2.jpg
  src/assets/Accessories/Accessories_3.jpg
  src/assets/Clothes/Clothes_1.jpg
  src/assets/Clothes/Clothes_2.jpg
  src/assets/Clothes/Clothes_3.jpg
  src/assets/Clothes/Clothes_4.jpg
  src/assets/Clothes/Clothes_5.jpg
  src/assets/Clothes/Clothes_6.jpg
  src/assets/Clothes/Clothes_7.jpg
  src/assets/Clothes/Clothes_8.jpg
  src/assets/Footwear/Footwear_1.jpg
  src/assets/Footwear/Footwear_3.jpg
  src/assets/Gender/Kid_1.jpg
  src/assets/Gender/Kids_2.jpg
  src/assets/Gender/Kids_3.jpg
  src/assets/Gender/Man_1.jpg
  src/assets/Gender/Woman_1.jpg
  src/components/Checkout/CheckoutForm.tsx
  src/components/Purchase/Purchase.tsx
Labels: bug

#68 Se crea componente admin-orders
  src/App.tsx
  src/components/Admin/Orders/Orders.module.scss
  src/components/Admin/Orders/Orders.tsx
  src/components/Purchase/Purchase.module.scss
  src/components/Purchase/Purchase.tsx
  src/redux/action/types.ts
  src/redux/reducer/index.ts
Labels: enhancement

#70 Pruebas de funcionamiento backend
  src/components/Checkout/CheckoutForm.tsx
  src/components/Purchase/Purchase.tsx
Labels: bug

#73 Feature admin orders get orders
  src/components/Admin/List/List.module.scss
  src/components/Admin/List/ListBill.tsx
  src/components/Admin/Orders/Orders.module.scss
  src/components/Admin/Orders/Orders.tsx
  src/components/Purchase/Purchase.tsx
Labels: enhancement

#79 se arregla errores de escritura en maquetado
  src/components/Admin/Orders/Orders.tsx
Labels: bug

#85 Cambio de imagen man y se agrega categoria deportes
  src/assets/Gender/Man_1.jpeg
  src/assets/Sport/Sport_1.jpg
  src/assets/Sport/Sport_2.jpg
  src/assets/Sport/Sport_3.jpg
  src/components/Admin/Orders/Graphic.module.scss
  src/components/Admin/Orders/Graphic.tsx
  src/components/Admin/Orders/Orders.tsx
  src/components/Categories/Categories.module.scss
  src/components/Categories/Categories.tsx
  src/components/Checkout/CheckoutForm.module.scss
  src/components/Checkout/CheckoutForm.tsx
  src/components/Purchase/Purchase.tsx
Labels: enhancement

#91 Se agrega componente OrderList con informacion de pedido
  src/App.tsx
  src/components/Admin/List/ListBill.tsx
  src/components/Admin/List/ListProduct.tsx
  src/components/Admin/List/OrderList.module.scss
  src/components/Admin/List/OrderList.tsx
  src/components/Admin/Orders/Order.module.scss
  src/components/Admin/Orders/Order.tsx
  src/components/Admin/Orders/Orders.tsx
  src/components/Admin/home/HomeAdmin.tsx
  src/components/Checkout/CheckoutForm.tsx
  src/redux/action/admin.ts
  src/redux/action/index.ts
  src/redux/reducer/admin.ts
  src/redux/reducer/index.ts
Labels: enhancement

#92 Fixed subcategory link correction
  src/components/Categories/Categories.tsx
  src/components/Subcategory/Subcategory.tsx
Labels: bug

#94 Ajustado CSS Paginacion
  src/components/productFilter/Product.module.scss
  src/components/productFilter/ProductFilter.tsx
Labels: bug

#95 bug
  src/App.tsx
Labels: bug

#96 Bug accesorios
  src/components/Subcategory/Subcategory.tsx
Labels: bug

#99 Se solucina inconveniente en componente Purchase
  src/components/Purchase/Purchase.tsx
Labels: bug

#111 Se arregla conexion con backend
  src/components/Cart/Cart.tsx
  src/components/Checkout/CheckoutForm.tsx
  src/components/Purchase/Purchase.tsx
  src/redux/action/index.ts
Labels: bug

#114 Se agrega subtotal en Purchase y se modifican redux-actions
  src/components/Purchase/Purchase.module.scss
  src/components/Purchase/Purchase.tsx
  src/redux/action/index.ts
  src/redux/action/types.ts
  src/redux/reducer/index.ts
Labels: enhancement

#116 Se agrega subtotal en purchase y se reconfigura otros componentes
  src/components/Admin/List/OrderList.module.scss
  src/components/Admin/List/OrderList.tsx
  src/components/Admin/Orders/Order.tsx
  src/components/Admin/Orders/OrderProgress.module.scss
  src/components/Admin/Orders/OrderProgress.tsx
  src/components/Categories/Categories.tsx
  src/components/Checkout/CheckoutForm.tsx
  src/components/Purchase/Purchase.tsx
  src/redux/action/admin.ts
  src/redux/action/index.ts
  src/redux/action/types.ts
  src/redux/reducer/admin.ts
Labels: enhancement

#128 Se agregan filtros a orderlist
  src/components/Admin/List/OrderList.module.scss
  src/components/Admin/List/OrderList.tsx
  src/components/Admin/Orders/Order.tsx
  src/redux/action/admin.ts
  src/redux/action/types.ts
  src/redux/reducer/admin.ts
Labels: enhancement

#141 Se crean componentes UserOrder y UserOrderList
  src/App.tsx
  src/components/UserOrder/UserOrder.tsx
  src/components/UserOrder/UserOrderList.module.scss
  src/components/UserOrder/UserOrderList.tsx
  src/redux/action/user.ts
  src/redux/reducer/user.ts
Labels: enhancement

#144 Conexion UserProfile con UserOrders
  src/components/UserOrder/UserOrderList.tsx
  src/routes/UserProfile.tsx
Labels: enhancement

#145 Eliminar shopinglist desde Checkoutform-Purchase
  src/components/Admin/List/OrderList.tsx
  src/components/Admin/Orders/OrderProgress.tsx
  src/components/Checkout/CheckoutForm.tsx
  src/components/Purchase/Purchase.tsx
  src/redux/action/admin.ts
  src/redux/action/index.ts
  src/redux/action/types.ts
  src/redux/reducer/admin.ts
Labels: enhancement

#155 Disable link Purchase
  src/components/Cart/Cart.tsx
Labels: enhancement
